<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE BLACKJACK [
<!ELEMENT BLACKJACK (TABLE)>
<!ELEMENT TABLE (DECK,PLAYER+,DEALER,ROUNDCOUNTER,TURN)>

<!--points to player who is playing-->
<!ELEMENT TURN (NAME)>
<!ELEMENT PLAYER (NAME,CARD+,MONEY,BET)>
<!ELEMENT DEALER (CARD+)>
<!ELEMENT MONEY (COIN*)>
<!ELEMENT BET (COIN+)>
<!ELEMENT DECK (CARD+)>

<!ELEMENT NAME (#PCDATA)>
<!ELEMENT CARD (#PCDATA)>
<!ELEMENT COIN (#PCDATA)> 

<!--optional-->
<!ELEMENT ROUNDCOUNTER (#PCDATA)>


<!ATTLIST CARD VALUE (1|2|3|4|5|6|7|8|9|10|11) #REQUIRED
                COLOR (HEART|DIAMOND|SPADE|CLUBS) #REQUIRED>
<!ATTLIST BLACKJACK GAMESTATE (dealing|bidding|playersTurn|dealerTurn|evaluation) #REQUIRED>
<!ATTLIST PLAYER PLAYERSTATE (playing|done|busted|waiting|oom) #REQUIRED>
<!ATTLIST DEALER DEALERSTATE (playing|done|busted|waiting) #REQUIRED>
]>

<BLACKJACK GAMESTATE="dealerTurn">
    <TABLE>
        <DECK>
            <CARD COLOR="HEART" VALUE="2"></CARD>
        </DECK>
        <PLAYER PLAYERSTATE="waiting">
            <NAME></NAME>
            <CARD COLOR="SPADE" VALUE="4"></CARD>
            <MONEY></MONEY>
            <BET>
                <COIN></COIN>
            </BET>
        </PLAYER>
        <DEALER DEALERSTATE="playing">
            <CARD COLOR="DIAMOND" VALUE="9"></CARD>
        </DEALER>
        <ROUNDCOUNTER></ROUNDCOUNTER>
        <TURN>
            <NAME></NAME>
        </TURN>
    </TABLE>
</BLACKJACK>
